version: "3.7"

services:
  greet:
    container_name: greet
    hostname: greet
    build:
      context: ./app
    ports:
      - '8080:80'
    command: -host=0.0.0.0 -port=80
  proxy:
    container_name: nginx-proxy
    hostname: proxy
    image: nginx
    volumes:
      - ./proxy/nginx.proxy.template:/etc/nginx/conf.d/nginx.proxy.template
      - type: volume
        source: proxy_logs
        target: /mnt/logs
    ports:
      - '8081:80'
    environment:
      - GREET_SCHEME=http
      - GREET_HOST=greet
      - GREET_PORT=80
    command:
      - /bin/bash
      - -c
      - "envsubst '$$GREET_SCHEME $$GREET_HOST $$GREET_PORT' < /etc/nginx/conf.d/nginx.proxy.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  exporter:
    container_name: exporter
    hostname: proxy
    image: quay.io/martinhelmich/prometheus-nginxlog-exporter
    volumes:
      - ./exporter/exporter.config.hcl:/etc/prometheus-nginxlog-exporter.hcl
      - type: volume
        source: proxy_logs
        target: /mnt/logs
    ports:
      - '8082:4040'
    environment:
      - LOG_FILE=/mnt/logs/proxy.access.log
    command: -config-file /etc/prometheus-nginxlog-exporter.hcl

volumes:
  proxy_logs: ~
